/** The endpoints provided by the Cronicle API. */
export type Endpoints =
  | 'get_schedule'
  | 'get_event'
  | 'create_event'
  | 'update_event'
  | 'delete_event'
  | 'get_event_history'
  | 'get_history'
  | 'run_event'
  | 'get_job_status'
  | 'get_active_jobs'
  | 'update_job'
  | 'abort_job'
  | 'get_master_state'
  | 'update_master_state'
